<?= $this->extend('layout/main') ?>

<?= $this->section('content') ?>
<?= $this->include('Modules\IMS\Views\partials\page_header') ?>

<?php
$formulation = is_array($formulation ?? null) ? $formulation : [];
$isEdit = $formulation !== [] && isset($formulation['id']);
$validation = is_array($validation ?? null) ? $validation : [];
$units = $units ?? [];
$users = $users ?? [];
$locations = $locations ?? [];
$currentUserId = (int) ($currentUserId ?? 0);
$hasOldInput = old('name') !== null;
$fmLang = static fn (string $key, array $args = []): string => lang('IMS.formulations.' . $key, $args);
$statusLabels = [
    'active' => $fmLang('status.active'),
    'approved' => $fmLang('status.approved'),
    'depleted' => $fmLang('status.depleted'),
    'expired' => $fmLang('status.expired'),
];
$typeLabels = [
    'Reagent mixture' => $fmLang('types.reagentMixture'),
    'Stock Solution' => $fmLang('types.stockSolution'),
    'Working solution' => $fmLang('types.workingSolution'),
    'Calibrator' => $fmLang('types.calibrator'),
];

$v = static function (string $name, string $default = '') use ($formulation, $hasOldInput): string {
    if ($hasOldInput) {
        $value = old($name);
        return $value !== null ? (string) $value : '';
    }

    return (string) ($formulation[$name] ?? $default);
};

$err = static function (string $name) use ($validation): void {
    if (isset($validation[$name])) {
        echo '<small class="admin-error">' . esc($validation[$name]) . '</small>';
    }
};

$sectionTitle = static function (string $title): void {
    echo '<p style="font-weight:600;font-size:0.82em;text-transform:uppercase;letter-spacing:.07em;color:var(--text-muted,#6c757d);margin:0 0 14px 0;padding-bottom:8px;border-bottom:1px solid var(--border-color,#dee2e6);">' . esc($title) . '</p>';
};

$select = static function (string $name, mixed $value) use ($v): string {
    return (string) $v($name) === (string) $value ? 'selected' : '';
};

$preparedByDefault = $isEdit ? '' : (string) $currentUserId;
$preparedDateDefault = $isEdit ? '' : date('Y-m-d');
?>

<div class="results-card ims-master-card ims-item-form-card">
    <div class="ims-master-toolbar">
        <div class="admin-card-head" style="padding-left:0;">
            <h3>
                <?php if ($isEdit) : ?>
                    <span class="tool-id-badge" style="font-size:0.75em;"><?= esc((string) ($formulation['formulation_lot'] ?? '')) ?></span>
                    <?= esc($fmLang('actions.edit')) ?>
                <?php else : ?>
                    <?= esc($fmLang('actions.add')) ?>
                <?php endif ?>
            </h3>
            <span><?= $isEdit ? esc((string) ($formulation['name'] ?? '')) : esc($fmLang('form.createHelp')) ?></span>
        </div>
        <div class="ims-toolbar-actions">
            <a class="admin-btn secondary" href="<?= esc(site_url('ims/formulations')) ?>">
                <i class="fa-solid fa-arrow-left"></i> <?= esc($fmLang('common.backToFormulations')) ?>
            </a>
        </div>
    </div>

    <div class="ims-item-form-body" style="padding:24px 24px 32px;">
        <?php if ($validation !== []) : ?>
            <div class="alert alert-danger" style="margin-bottom:20px;font-size:0.9em;">
                <?= esc($fmLang('common.correctErrors')) ?>
            </div>
        <?php endif ?>

        <form method="post" action="<?= $isEdit ? esc(site_url('ims/formulations/' . (int) $formulation['id'])) : esc(site_url('ims/formulations')) ?>">
            <?= csrf_field() ?>

            <div class="ims-item-form-panels" style="display:grid;grid-template-columns:1fr 1fr;gap:28px;margin-bottom:20px;">
                <div>
                    <div style="margin-bottom:28px;">
                        <?php $sectionTitle($fmLang('sections.basic')) ?>
                        <div class="admin-form-grid">
                            <div class="admin-form-group">
                                <label><?= esc($fmLang('fields.lotNo')) ?></label>
                                <input type="text" value="<?= esc($v('formulation_lot')) ?>" readonly placeholder="<?= esc($fmLang('form.autoGenerated')) ?>">
                                <small class="admin-muted"><?= esc($fmLang('form.lotHelp')) ?></small>
                            </div>
                            <div class="admin-form-group">
                                <label for="f-status"><?= esc($fmLang('columns.status')) ?> <span style="color:var(--danger,#dc3545);">*</span></label>
                                <select id="f-status" name="status" class="filter-select">
                                    <?php foreach ($statusLabels as $value => $label) : ?>
                                        <option value="<?= esc($value) ?>" <?= $select('status', $value) ?: (!$hasOldInput && ! $isEdit && $value === 'active' ? 'selected' : '') ?>><?= esc($label) ?></option>
                                    <?php endforeach ?>
                                </select>
                                <?php $err('status') ?>
                            </div>
                            <div class="admin-form-group full">
                                <label for="f-name"><?= esc($fmLang('fields.name')) ?> <span style="color:var(--danger,#dc3545);">*</span></label>
                                <input id="f-name" name="name" type="text" value="<?= esc($v('name')) ?>">
                                <?php $err('name') ?>
                            </div>
                            <div class="admin-form-group full">
                                <label for="f-type"><?= esc($fmLang('columns.type')) ?> <span style="color:var(--danger,#dc3545);">*</span></label>
                                <select id="f-type" name="formulation_type" class="filter-select">
                                    <option value=""><?= esc($fmLang('form.selectType')) ?></option>
                                    <?php foreach ($typeLabels as $type => $label) : ?>
                                        <option value="<?= esc($type) ?>" <?= $select('formulation_type', $type) ?>><?= esc($label) ?></option>
                                    <?php endforeach ?>
                                </select>
                                <?php $err('formulation_type') ?>
                            </div>
                        </div>
                    </div>

                    <div style="margin-bottom:28px;">
                        <?php $sectionTitle($fmLang('sections.quantity')) ?>
                        <div class="admin-form-grid">
                            <div class="admin-form-group">
                                <label for="f-qty"><?= esc($fmLang('fields.quantity')) ?> <span style="color:var(--danger,#dc3545);">*</span></label>
                                <input id="f-qty" name="qty" type="number" step="0.0001" min="0.0001" value="<?= esc($v('qty')) ?>">
                                <?php $err('qty') ?>
                            </div>
                            <div class="admin-form-group">
                                <label for="f-unit"><?= esc($fmLang('fields.unit')) ?> <span style="color:var(--danger,#dc3545);">*</span></label>
                                <select id="f-unit" name="unit_id" class="filter-select">
                                    <option value=""><?= esc($fmLang('form.selectUnit')) ?></option>
                                    <?php foreach ($units as $unit) : ?>
                                        <option value="<?= esc((string) $unit['id']) ?>" <?= $select('unit_id', $unit['id']) ?>><?= esc($unit['unit_name']) ?></option>
                                    <?php endforeach ?>
                                </select>
                                <?php $err('unit_id') ?>
                            </div>
                            <div class="admin-form-group">
                                <label for="f-concentration"><?= esc($fmLang('columns.concentration')) ?></label>
                                <input id="f-concentration" name="concentration" type="number" step="0.000001" value="<?= esc($v('concentration')) ?>">
                                <?php $err('concentration') ?>
                            </div>
                            <div class="admin-form-group">
                                <label for="f-concentration-unit"><?= esc($fmLang('fields.concentrationUnit')) ?></label>
                                <select id="f-concentration-unit" name="concentration_unit_id" class="filter-select">
                                    <option value=""><?= esc($fmLang('common.none')) ?></option>
                                    <?php foreach ($units as $unit) : ?>
                                        <option value="<?= esc((string) $unit['id']) ?>" <?= $select('concentration_unit_id', $unit['id']) ?>><?= esc($unit['unit_name']) ?></option>
                                    <?php endforeach ?>
                                </select>
                                <?php $err('concentration_unit_id') ?>
                            </div>
                        </div>
                    </div>

                    <div>
                        <?php $sectionTitle($fmLang('sections.storage')) ?>
                        <div class="admin-form-grid">
                            <div class="admin-form-group full">
                                <label for="f-location"><?= esc($fmLang('fields.storageLocation')) ?></label>
                                <select id="f-location" name="storage_location_id" class="filter-select">
                                    <option value=""><?= esc($fmLang('common.none')) ?></option>
                                    <?php foreach ($locations as $location) : ?>
                                        <option value="<?= esc((string) $location['id']) ?>" <?= $select('storage_location_id', $location['id']) ?>><?= esc($location['name']) ?></option>
                                    <?php endforeach ?>
                                </select>
                                <?php $err('storage_location_id') ?>
                            </div>
                        </div>
                    </div>
                </div>

                <div>
                    <div style="margin-bottom:28px;">
                        <?php $sectionTitle($fmLang('sections.preparation')) ?>
                        <div class="admin-form-grid">
                            <div class="admin-form-group">
                                <label for="f-prepared-date"><?= esc($fmLang('fields.preparedDate')) ?></label>
                                <input id="f-prepared-date" name="prepared_date" type="date" value="<?= esc($v('prepared_date', $preparedDateDefault)) ?>">
                                <?php $err('prepared_date') ?>
                            </div>
                            <div class="admin-form-group">
                                <label for="f-prepared-by"><?= esc($fmLang('fields.preparedBy')) ?></label>
                                <select id="f-prepared-by" name="prepared_by" class="filter-select">
                                    <option value=""><?= esc($fmLang('common.none')) ?></option>
                                    <?php foreach ($users as $user) : ?>
                                        <option value="<?= esc((string) $user['id']) ?>" <?= $select('prepared_by', $user['id']) ?: (!$hasOldInput && ! $isEdit && (string) $user['id'] === $preparedByDefault ? 'selected' : '') ?>><?= esc($user['username']) ?></option>
                                    <?php endforeach ?>
                                </select>
                                <?php $err('prepared_by') ?>
                            </div>
                            <div class="admin-form-group">
                                <label for="f-approved-date"><?= esc($fmLang('fields.approvedDate')) ?></label>
                                <input id="f-approved-date" name="approved_date" type="date" value="<?= esc($v('approved_date')) ?>">
                                <?php $err('approved_date') ?>
                            </div>
                            <div class="admin-form-group">
                                <label for="f-approved-by"><?= esc($fmLang('fields.approvedBy')) ?></label>
                                <select id="f-approved-by" name="approved_by" class="filter-select">
                                    <option value=""><?= esc($fmLang('common.none')) ?></option>
                                    <?php foreach ($users as $user) : ?>
                                        <option value="<?= esc((string) $user['id']) ?>" <?= $select('approved_by', $user['id']) ?>><?= esc($user['username']) ?></option>
                                    <?php endforeach ?>
                                </select>
                                <?php $err('approved_by') ?>
                            </div>
                            <div class="admin-form-group">
                                <label for="f-expired-date"><?= esc($fmLang('columns.expiry')) ?></label>
                                <input id="f-expired-date" name="expired_date" type="date" value="<?= esc($v('expired_date')) ?>">
                                <?php $err('expired_date') ?>
                            </div>
                        </div>
                    </div>

                    <div style="margin-bottom:28px;">
                        <?php $sectionTitle($fmLang('sections.retest')) ?>
                        <div class="admin-form-grid">
                            <div class="admin-form-group">
                                <label for="f-retest-date"><?= esc($fmLang('fields.retestDate')) ?></label>
                                <input id="f-retest-date" name="retest_date" type="date" value="<?= esc($v('retest_date')) ?>">
                                <?php $err('retest_date') ?>
                            </div>
                            <div class="admin-form-group">
                                <label for="f-retested-by"><?= esc($fmLang('fields.retestedBy')) ?></label>
                                <select id="f-retested-by" name="retested_by" class="filter-select">
                                    <option value=""><?= esc($fmLang('common.none')) ?></option>
                                    <?php foreach ($users as $user) : ?>
                                        <option value="<?= esc((string) $user['id']) ?>" <?= $select('retested_by', $user['id']) ?>><?= esc($user['username']) ?></option>
                                    <?php endforeach ?>
                                </select>
                                <?php $err('retested_by') ?>
                            </div>
                            <div class="admin-form-group">
                                <label for="f-retest-result"><?= esc($fmLang('fields.retestResult')) ?></label>
                                <input id="f-retest-result" name="retest_result" type="text" value="<?= esc($v('retest_result')) ?>">
                                <?php $err('retest_result') ?>
                            </div>
                            <div class="admin-form-group">
                                <label for="f-next-retest-date"><?= esc($fmLang('fields.nextRetestDate')) ?></label>
                                <input id="f-next-retest-date" name="next_retest_date" type="date" value="<?= esc($v('next_retest_date')) ?>">
                                <?php $err('next_retest_date') ?>
                            </div>
                            <div class="admin-form-group full">
                                <label for="f-retest-comment"><?= esc($fmLang('fields.retestComment')) ?></label>
                                <input id="f-retest-comment" name="retest_comment" type="text" value="<?= esc($v('retest_comment')) ?>">
                                <?php $err('retest_comment') ?>
                            </div>
                        </div>
                    </div>

                    <div>
                        <?php $sectionTitle($fmLang('sections.description')) ?>
                        <div class="admin-form-group">
                            <label for="f-description"><?= esc($fmLang('fields.description')) ?></label>
                            <textarea id="f-description" name="description" rows="5"><?= esc($v('description')) ?></textarea>
                            <?php $err('description') ?>
                        </div>
                    </div>
                </div>
            </div>

            <div class="ims-item-form-actions" style="display:flex;justify-content:flex-end;gap:12px;padding-top:20px;border-top:1px solid var(--border-color,#dee2e6);">
                <a class="admin-btn secondary" href="<?= esc(site_url('ims/formulations')) ?>"><?= esc($fmLang('common.cancel')) ?></a>
                <button type="submit" class="admin-btn primary">
                    <?= esc($isEdit ? $fmLang('actions.update') : $fmLang('actions.create')) ?>
                </button>
            </div>
        </form>
    </div>
</div>
<?= $this->endSection() ?>
