<?= $this->extend('layout/main') ?>

<?= $this->section('content') ?>
<?= $this->include('Modules\IMS\Views\partials\page_header') ?>

<?php
$item       = is_array($item ?? null) ? $item : [];
$isEdit     = $item !== [] && isset($item['id']);
$validation = is_array($validation ?? null) ? $validation : [];
$categories = $categories ?? [];
$units      = $units ?? [];

$itemLang = static fn (string $key, array $args = []): string => lang('IMS.items.' . $key, $args);

$hasOldInput = old('item_name') !== null;

$v = static function (string $name, string $default = '') use ($item, $hasOldInput): string {
    if ($hasOldInput) {
        $val = old($name);
        return $val !== null ? (string) $val : '';
    }
    return (string) ($item[$name] ?? $default);
};

$chk = static function (string $name, bool $defaultOn = false) use ($item, $hasOldInput): bool {
    if ($hasOldInput) {
        return old($name) === '1';
    }
    if (isset($item[$name])) {
        return (bool) $item[$name];
    }
    return $defaultOn;
};

$err = static function (string $name) use ($validation): void {
    if (isset($validation[$name])) {
        echo '<small class="admin-error">' . esc($validation[$name]) . '</small>';
    }
};

$sectionTitle = static function (string $title): void {
    echo '<p style="font-weight:600;font-size:0.82em;text-transform:uppercase;letter-spacing:.07em;color:var(--text-muted,#6c757d);margin:0 0 14px 0;padding-bottom:8px;border-bottom:1px solid var(--border-color,#dee2e6);">' . esc($title) . '</p>';
};
?>

<div class="results-card ims-master-card ims-item-form-card">
    <div class="ims-master-toolbar">
        <div class="admin-card-head" style="padding-left:0;">
            <h3>
                <?php if ($isEdit) : ?>
                    <span class="tool-id-badge" style="font-size:0.75em;"><?= esc((string) ($item['item_code'] ?? '')) ?></span>
                    <?= esc($itemLang('form.editTitle')) ?>
                <?php else : ?>
                    <?= esc($itemLang('form.addTitle')) ?>
                <?php endif ?>
            </h3>
            <span><?= $isEdit ? esc((string) ($item['item_name'] ?? '')) : esc($itemLang('form.intro')) ?></span>
        </div>
        <div class="ims-toolbar-actions">
            <a class="admin-btn secondary" href="<?= esc(site_url('ims/items')) ?>">
                <i class="fa-solid fa-arrow-left"></i> <?= esc($itemLang('common.backToItems')) ?>
            </a>
        </div>
    </div>

    <div class="ims-item-form-body" style="padding:24px 24px 32px;">
        <?php if ($validation !== []) : ?>
            <div class="alert alert-danger" style="margin-bottom:20px;font-size:0.9em;">
                <?= esc($itemLang('common.correctErrors')) ?>
            </div>
        <?php endif ?>

        <form method="post" action="<?= $isEdit ? esc(site_url('ims/items/' . (int) $item['id'])) : esc(site_url('ims/items')) ?>">
            <?= csrf_field() ?>

            <div class="ims-item-form-panels" style="display:grid;grid-template-columns:1fr 1fr;gap:28px;margin-bottom:20px;">
                <div>
                    <!-- Basic Information -->
                    <div style="margin-bottom:28px;">
                        <?php $sectionTitle($itemLang('sections.basicInformation')) ?>
                        <div class="admin-form-grid">
                            <div class="admin-form-group">
                                <label><?= esc($itemLang('fields.itemCode')) ?></label>
                                <input type="text" value="<?= esc($v('item_code')) ?>" readonly placeholder="<?= esc($itemLang('placeholders.autoGenerated')) ?>">
                                <small class="admin-muted"><?= esc($itemLang('help.itemCode')) ?></small>
                            </div>
                            <div class="admin-form-group">
                                <label for="f-status"><?= esc($itemLang('columns.status')) ?></label>
                                <select id="f-status" name="status" class="filter-select">
                                    <?php foreach (['active', 'inactive', 'blocked', 'obsolete'] as $val) : ?>
                                        <?php $label = $itemLang('status.' . $val); ?>
                                        <option value="<?= esc($val) ?>" <?= $v('status', 'active') === $val ? 'selected' : '' ?>><?= esc($label) ?></option>
                                    <?php endforeach ?>
                                </select>
                                <?php $err('status') ?>
                            </div>
                            <div class="admin-form-group full">
                                <label for="f-item-name"><?= esc($itemLang('fields.itemName')) ?> <span style="color:var(--danger,#dc3545);">*</span></label>
                                <input id="f-item-name" name="item_name" type="text" value="<?= esc($v('item_name')) ?>">
                                <?php $err('item_name') ?>
                            </div>
                            <div class="admin-form-group full">
                                <label for="f-alternate-name"><?= esc($itemLang('fields.alternateName')) ?></label>
                                <input id="f-alternate-name" name="alternate_name" type="text" value="<?= esc($v('alternate_name')) ?>" placeholder="<?= esc($itemLang('placeholders.alternateName')) ?>">
                                <?php $err('alternate_name') ?>
                            </div>
                        </div>
                    </div>

                    <!-- Chemical Identifiers -->
                    <div style="margin-bottom:28px;">
                        <?php $sectionTitle($itemLang('sections.chemicalIdentifiers')) ?>
                        <div class="admin-form-grid">
                            <div class="admin-form-group">
                                <label for="f-cas-no"><?= esc($itemLang('columns.casNo')) ?></label>
                                <input id="f-cas-no" name="cas_no" type="text" value="<?= esc($v('cas_no')) ?>" placeholder="<?= esc($itemLang('placeholders.casNo')) ?>">
                                <?php $err('cas_no') ?>
                            </div>
                            <div class="admin-form-group">
                                <label for="f-ec-no"><?= esc($itemLang('fields.ecNo')) ?></label>
                                <input id="f-ec-no" name="ec_no" type="text" value="<?= esc($v('ec_no')) ?>" placeholder="<?= esc($itemLang('placeholders.ecNo')) ?>">
                                <?php $err('ec_no') ?>
                            </div>
                        </div>
                    </div>

                    <!-- Classification -->
                    <div>
                        <?php $sectionTitle($itemLang('sections.classification')) ?>
                        <div class="admin-form-grid">
                            <div class="admin-form-group">
                                <label for="f-category-id"><?= esc($itemLang('columns.category')) ?> <span style="color:var(--danger,#dc3545);">*</span></label>
                                <select id="f-category-id" name="category_id" class="filter-select">
                                    <option value=""><?= esc($itemLang('placeholders.selectCategory')) ?></option>
                                    <?php foreach ($categories as $cat) : ?>
                                        <option value="<?= esc((string) $cat['id']) ?>" <?= $v('category_id') == $cat['id'] ? 'selected' : '' ?>><?= esc($cat['category_name']) ?></option>
                                    <?php endforeach ?>
                                </select>
                                <?php $err('category_id') ?>
                            </div>
                            <div class="admin-form-group">
                                <label for="f-default-unit-id"><?= esc($itemLang('fields.defaultUnit')) ?> <span style="color:var(--danger,#dc3545);">*</span></label>
                                <select id="f-default-unit-id" name="default_unit_id" class="filter-select">
                                    <option value=""><?= esc($itemLang('placeholders.selectUnit')) ?></option>
                                    <?php foreach ($units as $unit) : ?>
                                        <option value="<?= esc((string) $unit['id']) ?>" <?= $v('default_unit_id') == $unit['id'] ? 'selected' : '' ?>><?= esc($unit['unit_name']) ?></option>
                                    <?php endforeach ?>
                                </select>
                                <?php $err('default_unit_id') ?>
                            </div>
                        </div>
                    </div>
                </div>

                <div>
                    <!-- Stock Control -->
                    <div style="margin-bottom:28px;">
                        <?php $sectionTitle($itemLang('sections.stockControl')) ?>
                        <div class="admin-form-grid">
                            <div class="admin-form-group">
                                <label for="f-min-stock-level"><?= esc($itemLang('fields.minStockLevel')) ?></label>
                                <input id="f-min-stock-level" name="min_stock_level" type="number" step="0.0001" min="0" value="<?= esc($v('min_stock_level')) ?>">
                                <?php $err('min_stock_level') ?>
                            </div>
                            <div class="admin-form-group">
                                <label for="f-max-stock-level"><?= esc($itemLang('fields.maxStockLevel')) ?></label>
                                <input id="f-max-stock-level" name="max_stock_level" type="number" step="0.0001" min="0" value="<?= esc($v('max_stock_level')) ?>">
                                <?php $err('max_stock_level') ?>
                            </div>
                            <div class="admin-form-group">
                                <label for="f-reorder-level"><?= esc($itemLang('fields.reorderLevel')) ?></label>
                                <input id="f-reorder-level" name="reorder_level" type="number" step="0.0001" min="0" value="<?= esc($v('reorder_level')) ?>">
                                <?php $err('reorder_level') ?>
                            </div>
                        </div>
                    </div>

                    <!-- Description -->
                    <div>
                        <?php $sectionTitle($itemLang('fields.description')) ?>
                        <div class="admin-form-group">
                            <label for="f-description"><?= esc($itemLang('fields.description')) ?></label>
                            <textarea id="f-description" name="description" rows="4"><?= esc($v('description')) ?></textarea>
                            <?php $err('description') ?>
                        </div>
                    </div>
                </div>
            </div>

            <div class="ims-item-form-panels" style="display:grid;grid-template-columns:1fr 1fr;gap:28px;margin-bottom:20px;">
                <!-- Tracking & Compliance -->
                <div>
                    <?php $sectionTitle($itemLang('sections.trackingCompliance')) ?>
                    <div class="d-flex flex-wrap gap-4">
                        <?php foreach ([
                            'requires_expiry_tracking' => [$itemLang('fields.expiryTracking'), true],
                            'requires_lot_tracking'    => [$itemLang('fields.lotTracking'), true],
                            'requires_coa'             => [$itemLang('fields.coaRequired'), false],
                            'requires_sds'             => [$itemLang('fields.sdsRequired'), false],
                            'requires_special_storage' => [$itemLang('fields.specialStorage'), false],
                            'is_active'                => [$itemLang('status.active'), true],
                        ] as $name => [$label, $defaultOn]) : ?>
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" value="1"
                                    id="f-<?= esc(str_replace('_', '-', $name)) ?>"
                                    name="<?= esc($name) ?>"
                                    <?= $chk($name, $defaultOn) ? 'checked' : '' ?>>
                                <label class="form-check-label" for="f-<?= esc(str_replace('_', '-', $name)) ?>"><?= esc($label) ?></label>
                            </div>
                        <?php endforeach ?>
                    </div>
                </div>

                <!-- Hazard Classification -->
                <div>
                    <?php $sectionTitle($itemLang('sections.hazardClassification')) ?>
                    <div class="d-flex flex-wrap gap-4">
                        <?php foreach ([
                            'is_controlled_substance' => $itemLang('fields.controlledSubstance'),
                            'is_flammable'            => $itemLang('fields.flammable'),
                            'is_corrosive'            => $itemLang('fields.corrosive'),
                            'is_toxic'                => $itemLang('fields.toxic'),
                            'is_cmr'                  => $itemLang('fields.cmr'),
                        ] as $name => $label) : ?>
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" value="1"
                                    id="f-<?= esc(str_replace('_', '-', $name)) ?>"
                                    name="<?= esc($name) ?>"
                                    <?= $chk($name) ? 'checked' : '' ?>>
                                <label class="form-check-label" for="f-<?= esc(str_replace('_', '-', $name)) ?>"><?= esc($label) ?></label>
                            </div>
                        <?php endforeach ?>
                    </div>
                </div>
            </div>

            <!-- Actions -->
            <div class="ims-item-form-actions" style="display:flex;justify-content:flex-end;gap:12px;padding-top:20px;border-top:1px solid var(--border-color,#dee2e6);">
                <a class="admin-btn secondary" href="<?= esc(site_url('ims/items')) ?>"><?= esc($itemLang('common.cancel')) ?></a>
                <button type="submit" class="admin-btn primary">
                    <?= esc($isEdit ? $itemLang('form.update') : $itemLang('form.create')) ?>
                </button>
            </div>
        </form>
    </div>
</div>
<?= $this->endSection() ?>
