<?= $this->extend('layout/main') ?>

<?= $this->section('content') ?>
<?= $this->include('Modules\IMS\Views\partials\page_header') ?>

<?php
$item       = is_array($item ?? null) ? $item : [];
$lot        = is_array($lot ?? null) ? $lot : [];
$isEdit     = $lot !== [] && isset($lot['id']);
$validation = is_array($validation ?? null) ? $validation : [];
$suppliers  = $suppliers ?? [];
$brands     = $brands ?? [];
$units      = $units ?? [];
$locations  = $locations ?? [];

$itemLang = static fn (string $key, array $args = []): string => lang('IMS.items.' . $key, $args);

$hasOldInput = old('initial_qty') !== null;

$v = static function (string $name, string $default = '') use ($lot, $hasOldInput): string {
    if ($hasOldInput) {
        $val = old($name);
        return $val !== null ? (string) $val : '';
    }
    return (string) ($lot[$name] ?? $default);
};

$sel = static function (string $name, string $compareValue, string $default = '') use ($lot, $hasOldInput): string {
    $current = $hasOldInput ? (string) (old($name) ?? '') : (string) ($lot[$name] ?? $default);
    return $current === $compareValue ? ' selected' : '';
};

$err = static function (string $name) use ($validation): void {
    if (isset($validation[$name])) {
        echo '<small class="admin-error">' . esc($validation[$name]) . '</small>';
    }
};

$sectionTitle = static function (string $title): void {
    echo '<p style="font-weight:600;font-size:0.82em;text-transform:uppercase;letter-spacing:.07em;color:var(--text-muted,#6c757d);margin:0 0 12px 0;padding-bottom:7px;border-bottom:1px solid var(--border-color,#dee2e6);">' . esc($title) . '</p>';
};

$grid3 = 'grid-template-columns:repeat(3,minmax(0,1fr))';
$grid4 = 'grid-template-columns:repeat(4,minmax(0,1fr))';
?>

<div class="results-card ims-master-card ims-stock-lot-form-card">
    <div class="ims-master-toolbar">
        <div class="admin-card-head" style="padding-left:0;">
            <h3><?= esc($isEdit ? $itemLang('stockLotForm.editTitle') : $itemLang('stockLotForm.addTitle')) ?></h3>
            <span>
                <span class="tool-id-badge" style="font-size:0.78em;"><?= esc((string) ($item['item_code'] ?? '')) ?></span>
                <?= esc((string) ($item['item_name'] ?? '')) ?>
            </span>
        </div>
        <div class="ims-toolbar-actions">
            <a class="admin-btn secondary" href="<?= esc(site_url('ims/items/' . (int) ($item['id'] ?? 0))) ?>">
                <i class="fa-solid fa-arrow-left"></i> <?= esc($itemLang('common.backToItem')) ?>
            </a>
        </div>
    </div>

    <div class="ims-stock-lot-form-body" style="padding:20px 24px 28px;">
        <?php if ($validation !== []) : ?>
            <div class="alert alert-danger" style="margin-bottom:16px;font-size:0.9em;">
                <?= esc($itemLang('common.correctErrors')) ?>
            </div>
        <?php endif ?>

        <form method="post" action="<?= $isEdit
            ? esc(site_url('ims/items/' . (int) ($item['id'] ?? 0) . '/lots/' . (int) $lot['id']))
            : esc(site_url('ims/items/' . (int) ($item['id'] ?? 0) . '/lots')) ?>">
            <?= csrf_field() ?>
            <input type="hidden" name="item_id" value="<?= esc((string) ($item['id'] ?? '')) ?>">

            <!-- Top two-panel layout -->
            <div class="ims-stock-lot-form-panels" style="display:grid;grid-template-columns:1fr 1fr;gap:28px;margin-bottom:20px;">

                <!-- ── Left panel ── -->
                <div>
                    <!-- Lot Identification -->
                    <div style="margin-bottom:20px;">
                        <?php $sectionTitle($itemLang('sections.lotIdentification')) ?>
                        <div class="admin-form-grid" style="<?= $grid3 ?>">
                            <div class="admin-form-group">
                                <label><?= esc($itemLang('fields.internalLotNo')) ?></label>
                                <input type="text" value="<?= esc($v('internal_lot_no')) ?>" readonly placeholder="<?= esc($itemLang('placeholders.autoGenerated')) ?>">
                                <small class="admin-muted">L-00000001, ...</small>
                            </div>
                            <div class="admin-form-group">
                                <label for="f-lot-no"><?= esc($itemLang('columns.lot')) ?></label>
                                <input id="f-lot-no" name="lot_no" type="text" value="<?= esc($v('lot_no')) ?>" placeholder="<?= esc($itemLang('placeholders.manufacturerLotNo')) ?>">
                                <?php $err('lot_no') ?>
                            </div>
                            <div class="admin-form-group">
                                <label for="f-supplier-lot-no"><?= esc($itemLang('fields.supplierLotNo')) ?></label>
                                <input id="f-supplier-lot-no" name="supplier_lot_no" type="text" value="<?= esc($v('supplier_lot_no')) ?>">
                                <?php $err('supplier_lot_no') ?>
                            </div>
                            <div class="admin-form-group">
                                <label for="f-serial-no"><?= esc($itemLang('fields.serialNo')) ?></label>
                                <input id="f-serial-no" name="serial_no" type="text" value="<?= esc($v('serial_no')) ?>">
                                <?php $err('serial_no') ?>
                            </div>
                            <div class="admin-form-group">
                                <label for="f-type"><?= esc($itemLang('fields.itemType')) ?></label>
                                <input id="f-type" name="type" type="text" value="<?= esc($v('type')) ?>" placeholder="<?= esc($itemLang('placeholders.itemType')) ?>">
                                <?php $err('type') ?>
                            </div>
                        </div>
                    </div>

                    <!-- Supply Information -->
                    <div>
                        <?php $sectionTitle($itemLang('sections.supplyInformation')) ?>
                        <div class="admin-form-grid" style="<?= $grid3 ?>">
                            <div class="admin-form-group">
                                <label for="f-supplier-id"><?= esc($itemLang('columns.supplier')) ?></label>
                                <select id="f-supplier-id" name="supplier_id" class="filter-select">
                                    <option value=""><?= esc($itemLang('placeholders.noSupplier')) ?></option>
                                    <?php foreach ($suppliers as $s) : ?>
                                        <option value="<?= esc((string) $s['id']) ?>"<?= $sel('supplier_id', (string) $s['id']) ?>><?= esc($s['supplier_name']) ?></option>
                                    <?php endforeach ?>
                                </select>
                                <?php $err('supplier_id') ?>
                            </div>
                            <div class="admin-form-group">
                                <label for="f-catalog-no"><?= esc($itemLang('fields.catalogNo')) ?></label>
                                <input id="f-catalog-no" name="catalog_no" type="text" value="<?= esc($v('catalog_no')) ?>">
                                <?php $err('catalog_no') ?>
                            </div>
                            <div class="admin-form-group">
                                <label for="f-brand-id"><?= esc($itemLang('columns.brand')) ?></label>
                                <select id="f-brand-id" name="brand_id" class="filter-select">
                                    <option value=""><?= esc($itemLang('placeholders.noBrand')) ?></option>
                                    <?php foreach ($brands as $b) : ?>
                                        <option value="<?= esc((string) $b['id']) ?>"<?= $sel('brand_id', (string) $b['id']) ?>><?= esc($b['brand_name']) ?></option>
                                    <?php endforeach ?>
                                </select>
                                <?php $err('brand_id') ?>
                            </div>
                            <div class="admin-form-group">
                                <label for="f-grade"><?= esc($itemLang('fields.grade')) ?></label>
                                <input id="f-grade" name="grade" type="text" value="<?= esc($v('grade')) ?>" placeholder="<?= esc($itemLang('placeholders.grade')) ?>">
                                <?php $err('grade') ?>
                            </div>
                            <div class="admin-form-group">
                                <label for="f-pack-size"><?= esc($itemLang('fields.packSize')) ?></label>
                                <input id="f-pack-size" name="pack_size" type="text" value="<?= esc($v('pack_size')) ?>" placeholder="<?= esc($itemLang('placeholders.packSize')) ?>">
                                <?php $err('pack_size') ?>
                            </div>
                        </div>
                    </div>
                </div><!-- /left panel -->

                <!-- ── Right panel ── -->
                <div>
                    <!-- Dates -->
                    <div style="margin-bottom:20px;">
                        <?php $sectionTitle($itemLang('sections.dates')) ?>
                        <div class="admin-form-grid" style="<?= $grid3 ?>">
                            <div class="admin-form-group">
                                <label for="f-received-date"><?= esc($itemLang('dateLabels.received')) ?></label>
                                <input id="f-received-date" name="received_date" type="date" value="<?= esc($v('received_date')) ?>">
                                <?php $err('received_date') ?>
                            </div>
                            <div class="admin-form-group">
                                <label for="f-manufacture-date"><?= esc($itemLang('dateLabels.manufacture')) ?></label>
                                <input id="f-manufacture-date" name="manufacture_date" type="date" value="<?= esc($v('manufacture_date')) ?>">
                                <?php $err('manufacture_date') ?>
                            </div>
                            <div class="admin-form-group">
                                <label for="f-expiry-date"><?= esc($itemLang('dateLabels.expiry')) ?></label>
                                <input id="f-expiry-date" name="expiry_date" type="date" value="<?= esc($v('expiry_date')) ?>">
                                <?php $err('expiry_date') ?>
                            </div>
                            <div class="admin-form-group">
                                <label for="f-retest-date"><?= esc($itemLang('dateLabels.retest')) ?></label>
                                <input id="f-retest-date" name="retest_date" type="date" value="<?= esc($v('retest_date')) ?>">
                                <?php $err('retest_date') ?>
                            </div>
                            <div class="admin-form-group">
                                <label for="f-opened-date"><?= esc($itemLang('dateLabels.opened')) ?></label>
                                <input id="f-opened-date" name="opened_date" type="date" value="<?= esc($v('opened_date')) ?>">
                                <?php $err('opened_date') ?>
                            </div>
                        </div>
                    </div>

                    <!-- Quantities -->
                    <div>
                        <?php $sectionTitle($itemLang('sections.quantities')) ?>
                        <div class="admin-form-grid" style="<?= $grid4 ?>">
                            <div class="admin-form-group">
                                <label for="f-initial-qty"><?= esc($itemLang('fields.initialQty')) ?> <span style="color:var(--danger,#dc3545);">*</span></label>
                                <input id="f-initial-qty" name="initial_qty" type="number" step="0.0001" min="0" value="<?= esc($v('initial_qty')) ?>">
                                <?php $err('initial_qty') ?>
                            </div>
                            <div class="admin-form-group">
                                <label for="f-initial-unit-id"><?= esc($itemLang('fields.initialUnit')) ?> <span style="color:var(--danger,#dc3545);">*</span></label>
                                <select id="f-initial-unit-id" name="initial_unit_id" class="filter-select">
                                    <option value=""><?= esc($itemLang('placeholders.selectUnit')) ?></option>
                                    <?php foreach ($units as $u) : ?>
                                        <option value="<?= esc((string) $u['id']) ?>"<?= $sel('initial_unit_id', (string) $u['id']) ?>><?= esc($u['unit_name']) ?></option>
                                    <?php endforeach ?>
                                </select>
                                <?php $err('initial_unit_id') ?>
                            </div>
                            <div class="admin-form-group">
                                <label for="f-current-qty"><?= esc($itemLang('fields.currentQty')) ?> <span style="color:var(--danger,#dc3545);">*</span></label>
                                <input id="f-current-qty" name="current_qty" type="number" step="0.0001" min="0" value="<?= esc($v('current_qty')) ?>">
                                <?php $err('current_qty') ?>
                            </div>
                            <div class="admin-form-group">
                                <label for="f-current-unit-id"><?= esc($itemLang('fields.currentUnit')) ?> <span style="color:var(--danger,#dc3545);">*</span></label>
                                <select id="f-current-unit-id" name="current_unit_id" class="filter-select">
                                    <option value=""><?= esc($itemLang('placeholders.selectUnit')) ?></option>
                                    <?php foreach ($units as $u) : ?>
                                        <option value="<?= esc((string) $u['id']) ?>"<?= $sel('current_unit_id', (string) $u['id']) ?>><?= esc($u['unit_name']) ?></option>
                                    <?php endforeach ?>
                                </select>
                                <?php $err('current_unit_id') ?>
                            </div>
                            <div class="admin-form-group">
                                <label for="f-concentration-value"><?= esc($itemLang('fields.concentration')) ?></label>
                                <input id="f-concentration-value" name="concentration_value" type="number" step="0.000001" min="0" value="<?= esc($v('concentration_value')) ?>">
                                <?php $err('concentration_value') ?>
                            </div>
                            <div class="admin-form-group">
                                <label for="f-concentration-unit-id"><?= esc($itemLang('fields.concentrationUnit')) ?></label>
                                <select id="f-concentration-unit-id" name="concentration_unit_id" class="filter-select">
                                    <option value=""><?= esc($itemLang('placeholders.noUnit')) ?></option>
                                    <?php foreach ($units as $u) : ?>
                                        <option value="<?= esc((string) $u['id']) ?>"<?= $sel('concentration_unit_id', (string) $u['id']) ?>><?= esc($u['unit_name']) ?></option>
                                    <?php endforeach ?>
                                </select>
                                <?php $err('concentration_unit_id') ?>
                            </div>
                            <div class="admin-form-group">
                                <label for="f-purity-value"><?= esc($itemLang('fields.purity')) ?></label>
                                <input id="f-purity-value" name="purity_value" type="number" step="0.0001" min="0" max="100" value="<?= esc($v('purity_value')) ?>">
                                <?php $err('purity_value') ?>
                            </div>
                        </div>
                    </div>
                </div><!-- /right panel -->
            </div><!-- /top two-panel -->

            <!-- Bottom two-panel: Storage & Remarks -->
            <div class="ims-stock-lot-form-panels" style="display:grid;grid-template-columns:1fr 1fr;gap:28px;margin-bottom:20px;">
                <!-- Storage & Ownership -->
                <div>
                    <?php $sectionTitle($itemLang('sections.storageOwnership')) ?>
                    <div class="admin-form-grid">
                        <div class="admin-form-group">
                            <label for="f-storage-location-id"><?= esc($itemLang('columns.location')) ?></label>
                            <select id="f-storage-location-id" name="storage_location_id" class="filter-select">
                                <option value=""><?= esc($itemLang('placeholders.noLocation')) ?></option>
                                <?php foreach ($locations as $loc) : ?>
                                    <option value="<?= esc((string) $loc['id']) ?>"<?= $sel('storage_location_id', (string) $loc['id']) ?>><?= esc($loc['name']) ?></option>
                                <?php endforeach ?>
                            </select>
                            <?php $err('storage_location_id') ?>
                        </div>
                        <div class="admin-form-group">
                            <label for="f-ownership-status"><?= esc($itemLang('columns.ownership')) ?></label>
                            <select id="f-ownership-status" name="ownership_status" class="filter-select">
                                <option value="owned"<?= $sel('ownership_status', 'owned', 'owned') ?>><?= esc($itemLang('ownership.owned')) ?></option>
                                <option value="consigned"<?= $sel('ownership_status', 'consigned', 'owned') ?>><?= esc($itemLang('ownership.consigned')) ?></option>
                                <option value="borrowed"<?= $sel('ownership_status', 'borrowed', 'owned') ?>><?= esc($itemLang('ownership.borrowed')) ?></option>
                            </select>
                            <?php $err('ownership_status') ?>
                        </div>
                    </div>
                </div>

                <!-- Remarks -->
                <div>
                    <?php $sectionTitle($itemLang('fields.remarks')) ?>
                    <div class="admin-form-group">
                        <label for="f-remarks"><?= esc($itemLang('fields.remarks')) ?></label>
                        <textarea id="f-remarks" name="remarks" rows="3"><?= esc($v('remarks')) ?></textarea>
                        <?php $err('remarks') ?>
                    </div>
                </div>
            </div><!-- /bottom two-panel -->

            <!-- Actions -->
            <div class="ims-stock-lot-form-actions" style="display:flex;justify-content:flex-end;gap:12px;padding-top:16px;border-top:1px solid var(--border-color,#dee2e6);">
                <a class="admin-btn secondary" href="<?= esc(site_url('ims/items/' . (int) ($item['id'] ?? 0))) ?>"><?= esc($itemLang('common.cancel')) ?></a>
                <button type="submit" class="admin-btn primary">
                    <?= esc($isEdit ? $itemLang('stockLotForm.update') : $itemLang('stockLotForm.create')) ?>
                </button>
            </div>
        </form>
    </div>
</div>
<?= $this->endSection() ?>
